### ISSUE TITLE
Remoção dos headers/footers e número de página do arquivo texto

### ISSUE THREAD

**Issue by josircg** [bonfimjustino7/larhub#1]
Antes de iniciar a geração da nuvem, remover os cabeçalhos e rodapés fixos do PDF.

O algoritmo vai assumir que se uma linha aparece várias vezes no texto, então ela é um header ou um footer. 

O primeiro passo é retirar todos os números soltos do texto para já remover os números de páginas que possam existir.

A partir, temos que contar quantas vezes uma mesma linha aparece e se for mais de 2, remover a linha do arquivo texto.

**Comment by bonfimjustino7** [comment]
Isso é no PDF?
Você me mandou aquele arquivo que faz a conversão, ele resolve?


Em sex, 13 de set de 2019 às 08:41, Josir Cardoso Gomes <
notifications@github.com> escreveu:

**Comment by josircg** [comment]
Não. Isso já é no txt gerado. Quando eu subir a rotina, vc vai entender.
